<?php

namespace App\Modules\Payroll\Types;

final class PayrollEarningType
{
    public const BASIC_SALARY = 'BASIC_SALARY';
    public const ADDITIONAL_SALARY = 'ADDITIONAL_SALARY';
    public const INCENTIVE_SUNDAY_ROSTER = 'INCENTIVE_SUNDAY_ROSTER';
    public const INCENTIVE_HOME_VISIT = 'INCENTIVE_HOME_VISIT';
    public const INCENTIVE_SPEECH_THERAPY = 'INCENTIVE_SPEECH_THERAPY';
    public const INCENTIVE_DRY_NEEDLING = 'INCENTIVE_DRY_NEEDLING';
    public const ALLOWANCE_ALLIED_HEALTH_COUNCIL = 'ALLOWANCE_ALLIED_HEALTH_COUNCIL';
    public const ALLOWANCE_HOUSE_JOB = 'ALLOWANCE_HOUSE_JOB';
    public const ALLOWANCE_CONVEYANCE = 'ALLOWANCE_CONVEYANCE';
    public const ALLOWANCE_MEDICAL = 'ALLOWANCE_MEDICAL';
    public const ALLOWANCE_HOUSE_RENT = 'ALLOWANCE_HOUSE_RENT';
    public const OTHER_ALLOWANCE = 'OTHER_ALLOWANCE';
    public const OVERTIME = 'OVERTIME';
    public const SATISFACTORY_SESSIONS = 'SATISFACTORY_SESSIONS';
    public const TREATMENT_EXTENSION_COMMISSION = 'TREATMENT_EXTENSION_COMMISSION';
    public const SATISFACTION_BONUS = 'SATISFACTION_BONUS';
    public const ASSESSMENT_BONUS = 'ASSESSMENT_BONUS';
    public const REFERENCE_BONUS = 'REFERENCE_BONUS';
    public const PERSONAL_PATIENT_COMMISSION = 'PERSONAL_PATIENT_COMMISSION';
    public const CUSTOM = 'CUSTOM';
}
